/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialog;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

import org.apache.ibatis.session.SqlSession;

import factory.Factory;
import vo.DeptVO;
import vo.EmpVO;
import vo.MemberVO;

/**
 *
 * @author a
 */
public class change_emp extends javax.swing.JDialog {
	Detail_emp detail_emp;

    /**
     * Creates new form Change_emp2
     * @wbp.parser.constructor
     */
    public change_emp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public change_emp(Detail_emp detail_emp) {
		this.detail_emp = detail_emp;
		initComponents();
		D_change_emp_tf_empno.setText(detail_emp.D_detail_emp_tf_empno.getText());
		D_change_emp_tf_company.setText(detail_emp.D_detail_emp_tf_company.getText());
		D_change_emp_tf_id.setText(detail_emp.D_detail_emp_tf_id.getText());
		D_change_emp_tf_ename.setText(detail_emp.D_detail_emp_tf_ename.getText());
		D_change_emp_tf_password.setText(detail_emp.D_detail_emp_tf_password.getText());
		D_change_emp_cb_dept.setSelectedItem(detail_emp.D_detail_emp_tf_dept.getText());
		D_change_emp_cb_position.setSelectedItem(detail_emp.D_detail_emp_tf_position.getText());
		SqlSession ss = Factory.getFactory().openSession();
		
		  String empno = D_change_emp_tf_empno.getText();
	      EmpVO evo = ss.selectOne("emp.searchEmp", empno);
	      String gender = evo.getGender();
	      D_change_emp_cb_gender.setSelectedItem(gender);
	      String fireDate = evo.getFire_date();

	      if (fireDate != null) {
	        D_change_emp_cb_leave.setSelected(true);
	      } else {
	        D_change_emp_cb_leave.setSelected(false);
	      }

	      if(ss != null)
	         ss.close();
	      
		D_change_emp_cb_auth.setSelectedItem(detail_emp.D_detail_emp_tf_auth.getText());
		D_change_emp_tf_phone.setText(detail_emp.D_detail_emp_tf_phone.getText());
		D_change_emp_tf_birth.setText(detail_emp.D_detail_emp_tf_birth.getText());
		D_change_emp_tf_job.setText(detail_emp.D_detail_emp_tf_job.getText());
		D_change_emp_tf_hiredate.setText(detail_emp.D_detail_emp_tf_hiredate.getText());
		D_change_emp_tf_hobby.setText(detail_emp.D_detail_emp_tf_hobby.getText());
		D_change_emp_tf_speciality.setText(detail_emp.D_detail_emp_tf_speciality.getText());
		D_change_emp_tf_add.setText(detail_emp.D_detail_emp_tf_add.getText());
		D_change_emp_tf_account.setText(detail_emp.D_detail_emp_tf_account.getText());
		D_change_emp_cb_bank.setSelectedItem(detail_emp.D_detail_emp_cb_bank.getSelectedItem());
		D_change_emp_cb_employment.setSelectedItem(detail_emp.D_detail_emp_cb_employment.getSelectedItem());
		if (detail_emp.D_detail_emp_cb_venter.getSelectedItem() == "0") {
			D_change_emp_cb_venter.setSelectedIndex(1);
	    }else if (detail_emp.D_detail_emp_cb_venter.getSelectedItem() == "1") {
	    	D_change_emp_cb_venter.setSelectedIndex(0);  
	    }
		if (detail_emp.D_detail_emp_cb_obstacle.getSelectedItem() == "0") {
			D_change_emp_cb_obstacle.setSelectedIndex(1);
	    }else if (detail_emp.D_detail_emp_cb_obstacle.getSelectedItem() == "0") {
	    	D_change_emp_cb_obstacle.setSelectedIndex(0);  
	    }
		this.setVisible(true);
		
		
	}
    
    public int updateEmp(EmpVO evo) {
		SqlSession ss = Factory.getFactory().openSession();
		
		int cnt = ss.insert("emp.update", evo);
		
		if(cnt > 0)
			ss.commit();
		else
			ss.rollback();

		if(ss != null)
			ss.close();
		
		return cnt;
	}

    public int updateMember(MemberVO mvo) {
		SqlSession ss = Factory.getFactory().openSession();
		
		int cnt = ss.insert("member.update", mvo);
		
		if(cnt > 0)
			ss.commit();
		else
			ss.rollback();

		if(ss != null)
			ss.close();
		
		return cnt;
	}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_change_emp_jp = new javax.swing.JPanel();
        D_change_emp_lb_title = new javax.swing.JLabel();
        D_change_js_line1 = new javax.swing.JSeparator();
        D_change_emp_lb_ename = new javax.swing.JLabel();
        D_change_emp_lb_empno = new javax.swing.JLabel();
        D_change_emp_lb_employment = new javax.swing.JLabel();
        D_change_emp_lb_auth = new javax.swing.JLabel();
        D_change_js_line2 = new javax.swing.JSeparator();
        D_change_emp_lb_title2 = new javax.swing.JLabel();
        D_change_emp_lb_account = new javax.swing.JLabel();
        D_change_emp_tf_empno = new javax.swing.JTextField();
        D_change_emp_tf_id = new javax.swing.JTextField();
        D_change_emp_tf_password = new javax.swing.JTextField();
        D_change_emp_tf_account = new javax.swing.JTextField();
        D_change_emp_bt_save = new javax.swing.JButton();
        D_change_emp_bt_cancel = new javax.swing.JButton();
        D_change_emp_lb_id = new javax.swing.JLabel();
        D_change_emp_lb_dept = new javax.swing.JLabel();
        D_change_emp_lb_job = new javax.swing.JLabel();
        D_change_emp_tf_job = new javax.swing.JTextField();
        D_change_emp_tf_ename = new javax.swing.JTextField();
        D_change_emp_lb_bank = new javax.swing.JLabel();
        D_change_emp_lb_password = new javax.swing.JLabel();
        D_change_emp_lb_position = new javax.swing.JLabel();
        D_change_emp_lb_phone = new javax.swing.JLabel();
        D_change_emp_tf_phone = new javax.swing.JTextField();
        D_change_emp_lb_birth = new javax.swing.JLabel();
        D_change_emp_lb_hiredate = new javax.swing.JLabel();
        D_change_emp_tf_hiredate = new javax.swing.JTextField();
        D_change_emp_lb_hobby = new javax.swing.JLabel();
        D_change_emp_tf_hobby = new javax.swing.JTextField();
        D_change_emp_cb_leave = new javax.swing.JCheckBox();
        D_change_emp_lb_speciality = new javax.swing.JLabel();
        D_change_emp_tf_speciality = new javax.swing.JTextField();
        D_change_emp_lb_venter = new javax.swing.JLabel();
        D_change_emp_lb_obstacle = new javax.swing.JLabel();
        D_change_emp_tf_birth = new javax.swing.JTextField();
        D_change_emp_lb_company = new javax.swing.JLabel();
        D_change_emp_tf_company = new javax.swing.JTextField();
        D_change_emp_cb_bank = new javax.swing.JComboBox<>();
        D_change_emp_cb_employment = new javax.swing.JComboBox<>();
        D_change_emp_cb_obstacle = new javax.swing.JComboBox<>();
        D_change_emp_cb_venter = new javax.swing.JComboBox<>();
        D_change_emp_lb_address = new javax.swing.JLabel();
        D_change_emp_tf_add = new javax.swing.JTextField();
        D_change_emp_cb_auth = new javax.swing.JComboBox<>();
        D_change_emp_cb_gender = new javax.swing.JComboBox<>();
        D_change_emp_lb_gender = new javax.swing.JLabel();
        D_change_emp_cb_position = new javax.swing.JComboBox<>();
        D_change_emp_cb_dept = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));

        D_change_emp_jp.setBackground(new java.awt.Color(255, 255, 255));
        D_change_emp_jp.setMaximumSize(new java.awt.Dimension(800, 550));

        D_change_emp_lb_title.setFont(new java.awt.Font("맑은 고딕", 1, 22)); // NOI18N
        D_change_emp_lb_title.setText("구성원 수정");

        D_change_emp_lb_ename.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_ename.setText("이름*");

        D_change_emp_lb_empno.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_empno.setText("사번*");

        D_change_emp_lb_employment.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_employment.setText("직원구분");

        D_change_emp_lb_auth.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_auth.setText("권한");

        D_change_emp_lb_title2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        D_change_emp_lb_title2.setForeground(new java.awt.Color(51, 153, 255));
        D_change_emp_lb_title2.setText("계좌정보");

        D_change_emp_lb_account.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_account.setText("계좌번호");

        D_change_emp_tf_empno.setText("jTextField1");
        D_change_emp_tf_empno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_tf_empnoActionPerformed(evt);
            }
        });

        D_change_emp_tf_id.setText("jTextField1");

        D_change_emp_tf_password.setText("jTextField1");

        D_change_emp_tf_account.setText("jTextField1");
        D_change_emp_tf_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_tf_accountActionPerformed(evt);
            }
        });

        D_change_emp_bt_save.setBackground(new java.awt.Color(0, 153, 255));
        D_change_emp_bt_save.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_bt_save.setForeground(new java.awt.Color(255, 255, 255));
        D_change_emp_bt_save.setText("저장");
        D_change_emp_bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_bt_saveActionPerformed(evt);
            }
        });

        D_change_emp_bt_cancel.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_bt_cancel.setText("취소");
        D_change_emp_bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_bt_cancelActionPerformed(evt);
            }
        });

        D_change_emp_lb_id.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_id.setText("아이디*");

        D_change_emp_lb_dept.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_dept.setText("부서명");

        D_change_emp_lb_job.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_job.setText("직종");

        D_change_emp_tf_job.setText("jTextField1");

        D_change_emp_tf_ename.setText("jTextField1");
        D_change_emp_tf_ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_tf_enameActionPerformed(evt);
            }
        });

        D_change_emp_lb_bank.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_bank.setText("은행정보");

        D_change_emp_lb_password.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_password.setText("비밀번호");

        D_change_emp_lb_position.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_position.setText("직책");

        D_change_emp_lb_phone.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_phone.setText("휴대폰번호");

        D_change_emp_tf_phone.setText("jTextField1");

        D_change_emp_lb_birth.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_birth.setText("생년월일");

        D_change_emp_lb_hiredate.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_hiredate.setText("입사일");

        D_change_emp_tf_hiredate.setText("jTextField1");

        D_change_emp_lb_hobby.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_hobby.setText("취미");

        D_change_emp_tf_hobby.setText("jTextField1");

        D_change_emp_cb_leave.setText("퇴사처리");
        D_change_emp_cb_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_cb_leaveActionPerformed(evt);
            }
        });

        D_change_emp_lb_speciality.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_speciality.setText("특기");

        D_change_emp_tf_speciality.setText("jTextField1");

        D_change_emp_lb_venter.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_venter.setText("보훈여부");

        D_change_emp_lb_obstacle.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_obstacle.setText("장애여부");

        D_change_emp_tf_birth.setText("jTextField1");

        D_change_emp_lb_company.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_company.setText("소속");

        D_change_emp_tf_company.setText("jTextField1");

        D_change_emp_cb_bank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KEB하나은행", "SC제일은행", "국민은행", "신한은행", "외환은행", "우리은행", "농협", "한국시티은행", "카카오뱅크", "토스", "기업은행", "신협" }));
        D_change_emp_cb_bank.setToolTipText("");
        D_change_emp_cb_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_cb_bankActionPerformed(evt);
            }
        });

        D_change_emp_cb_employment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "정규직", "비정규직" }));
        D_change_emp_cb_employment.setToolTipText("");
        D_change_emp_cb_employment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_cb_employmentActionPerformed(evt);
            }
        });

        D_change_emp_cb_obstacle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "N" }));
        D_change_emp_cb_obstacle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_cb_obstacleActionPerformed(evt);
            }
        });

        D_change_emp_cb_venter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "N" }));

        D_change_emp_lb_address.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_address.setText("주소");

        D_change_emp_tf_add.setText("jTextField1");

        D_change_emp_cb_auth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "사원", "팀장", "관리자" }));

        D_change_emp_cb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "남", "여" }));
        D_change_emp_cb_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_change_emp_cb_genderActionPerformed(evt);
            }
        });

        D_change_emp_lb_gender.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_change_emp_lb_gender.setText("성별");

        D_change_emp_cb_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "사원", "주임", "대리", "과장", "부장" }));

        D_change_emp_cb_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "영업팀", "기획팀", "개발1팀", "개발2팀" }));

        javax.swing.GroupLayout D_change_emp_jpLayout = new javax.swing.GroupLayout(D_change_emp_jp);
        D_change_emp_jp.setLayout(D_change_emp_jpLayout);
        D_change_emp_jpLayout.setHorizontalGroup(
            D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_change_emp_lb_empno)
                            .addComponent(D_change_emp_lb_auth)
                            .addComponent(D_change_emp_lb_id)
                            .addComponent(D_change_emp_lb_password)
                            .addComponent(D_change_emp_lb_position)
                            .addComponent(D_change_emp_lb_employment)
                            .addComponent(D_change_emp_lb_hobby)
                            .addComponent(D_change_emp_lb_venter)
                            .addComponent(D_change_emp_lb_birth)
                            .addComponent(D_change_emp_lb_address))
                        .addGap(87, 87, 87)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(D_change_emp_cb_venter, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(D_change_emp_tf_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(D_change_emp_tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D_change_emp_tf_empno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(D_change_emp_cb_auth, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(D_change_emp_tf_birth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                    .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(D_change_emp_cb_position, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(D_change_emp_tf_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                    .addComponent(D_change_emp_cb_employment, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D_change_emp_lb_hiredate)
                                    .addComponent(D_change_emp_lb_speciality)
                                    .addComponent(D_change_emp_lb_dept)
                                    .addComponent(D_change_emp_lb_job)
                                    .addComponent(D_change_emp_lb_ename)
                                    .addComponent(D_change_emp_lb_obstacle)
                                    .addComponent(D_change_emp_lb_phone)
                                    .addComponent(D_change_emp_lb_company)
                                    .addComponent(D_change_emp_lb_gender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(D_change_emp_cb_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(D_change_emp_tf_speciality)
                                    .addComponent(D_change_emp_cb_obstacle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(D_change_emp_tf_hiredate)
                                    .addComponent(D_change_emp_tf_job)
                                    .addComponent(D_change_emp_tf_phone)
                                    .addComponent(D_change_emp_tf_ename)
                                    .addComponent(D_change_emp_tf_company)
                                    .addComponent(D_change_emp_cb_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addComponent(D_change_emp_tf_add, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(141, 141, 141))
                    .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                            .addComponent(D_change_emp_lb_title)
                            .addGap(18, 18, 18)
                            .addComponent(D_change_emp_cb_leave))
                        .addComponent(D_change_js_line1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                        .addComponent(D_change_js_line2))))
            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                                .addComponent(D_change_emp_lb_title2)
                                .addGap(373, 373, 373))
                            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                                .addComponent(D_change_emp_lb_account)
                                .addGap(18, 18, 18)
                                .addComponent(D_change_emp_tf_account, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(D_change_emp_lb_bank)))
                        .addGap(18, 18, 18)
                        .addComponent(D_change_emp_cb_bank, 0, 220, Short.MAX_VALUE)
                        .addGap(83, 83, 83))
                    .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                        .addComponent(D_change_emp_bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(D_change_emp_bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))))
        );
        D_change_emp_jpLayout.setVerticalGroup(
            D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_change_emp_lb_title)
                    .addComponent(D_change_emp_cb_leave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_change_js_line1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_tf_empno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_change_emp_lb_empno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_change_emp_tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_change_emp_lb_id, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_lb_password)
                                    .addComponent(D_change_emp_tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_lb_position)
                                    .addComponent(D_change_emp_cb_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_lb_auth)
                                    .addComponent(D_change_emp_cb_auth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_tf_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D_change_emp_lb_birth))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_lb_employment)
                                    .addComponent(D_change_emp_cb_employment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(D_change_emp_lb_venter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(D_change_emp_lb_hobby))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_change_emp_jpLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(D_change_emp_cb_venter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(D_change_emp_tf_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_lb_address)
                            .addComponent(D_change_emp_tf_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(D_change_js_line2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_change_emp_lb_title2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_lb_account)
                            .addComponent(D_change_emp_tf_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_change_emp_lb_bank)
                            .addComponent(D_change_emp_cb_bank))
                        .addGap(18, 18, 18)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_bt_save)
                            .addComponent(D_change_emp_bt_cancel))
                        .addGap(14, 14, 14))
                    .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_tf_company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_change_emp_lb_company))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_tf_ename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_change_emp_lb_ename))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_lb_dept)
                            .addComponent(D_change_emp_cb_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(D_change_emp_jpLayout.createSequentialGroup()
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_lb_phone)
                                    .addComponent(D_change_emp_tf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D_change_emp_lb_job)
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_change_emp_jpLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D_change_emp_tf_job, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_lb_hiredate)
                                    .addComponent(D_change_emp_tf_hiredate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_cb_obstacle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D_change_emp_lb_obstacle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D_change_emp_tf_speciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D_change_emp_lb_speciality))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(D_change_emp_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_change_emp_cb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_change_emp_lb_gender))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(D_change_emp_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(D_change_emp_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_change_emp_tf_empnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_tf_empnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_change_emp_tf_empnoActionPerformed

    private void D_change_emp_tf_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_tf_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_change_emp_tf_accountActionPerformed

    private void D_change_emp_bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_bt_saveActionPerformed
    	EmpVO evo = new EmpVO();
        
        String empno = D_change_emp_tf_empno.getText().trim();
        if(empno.length() == 0)
           empno = null;
        evo.setEmpno(Integer.parseInt(empno));
        
        String company = D_change_emp_tf_company.getText().trim();
        if(company.length() == 0)
           company = null;
        evo.setBelong(company);
        
        String ename = D_change_emp_tf_ename.getText().trim();
        if(ename.length() == 0)
           ename = null;
        evo.setEname(ename);
        
        String position = D_change_emp_cb_position.getSelectedItem().toString();
        if(position.length() == 0)
           position = null;
        evo.setPosition(position);
        
        
        String phone = D_change_emp_tf_phone.getText().trim();
        if(phone.length() == 0)
           phone = null;
        evo.setPhone(phone);
        
        String birth = D_change_emp_tf_birth.getText().trim();
        if(birth.length() == 0)
           birth= null;
        evo.setBirth(birth);
        
        String job = D_change_emp_tf_job.getText().trim();
        if(job.length() == 0)
           job = null;
        evo.setJob(job);
        
        String hiredate = D_change_emp_tf_hiredate.getText().trim();
        if(hiredate.length() == 0)
           hiredate = null;
        evo.setHiredate(hiredate);
        
        String hobby = D_change_emp_tf_hobby.getText().trim();
        if(hobby.length() == 0)
           hobby = null;
        evo.setHobby(hobby);
        
        String speciality = D_change_emp_tf_speciality.getText().trim();
        if(speciality.length() == 0)
           speciality = null;
        evo.setSpecialty(speciality);
        
        String add = D_change_emp_tf_add.getText().trim();
        if(add.length() == 0)
           add = null;
        evo.setAddress(add);
        
        String account = D_change_emp_tf_account.getText().trim();
        if(account.length() == 0)
           account = null;
        evo.setAccount_number(account);
        
        String venter = D_change_emp_cb_venter.getSelectedItem().toString();
        int v_value = venter.equals("Y")?1:0;
        evo.setVerterans(v_value);
        
        String obstacle = D_change_emp_cb_obstacle.getSelectedItem().toString();
        int o_value = obstacle.equals("Y")?1:0;
        evo.setObstacle(o_value);
        
        String bank = D_change_emp_cb_bank.getSelectedItem().toString();
        evo.setBank_info(bank);
        
        String employment = D_change_emp_cb_employment.getSelectedItem().toString();
        evo.setEmployment(employment);
        
        String gender = D_change_emp_cb_gender.getSelectedItem().toString();
        evo.setGender(gender);
        
        String dept = D_change_emp_cb_dept.getSelectedItem().toString(); //부서명
        
        SqlSession ss = Factory.getFactory().openSession();
        
        DeptVO dvo = ss.selectOne("dept.dept", dept);
        evo.setDvo(dvo);
        evo.setDeptno(dvo.getDeptno());
        
        Date currentDate = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String currentDateString = formatter.format(currentDate);
        
        if (D_change_emp_cb_leave.isSelected()) {
            evo.setJoin_status("1");
            evo.setFire_date(currentDateString);
        } else {
            evo.setJoin_status("0");
            evo.setFire_date(null);
        }
        
        if(ss != null)
           ss.close();
        
        //public MemberVO(int empno, int a_cate, int deptno, String id, String pw)
        String id = D_change_emp_tf_id.getText().trim();
        if(id.length() == 0)
        id = null;

        String password = D_change_emp_tf_password.getText().trim();
        if(password.length() == 0)
        password = null;
         
        int auth = D_change_emp_cb_auth.getSelectedIndex();
        MemberVO mvo = new MemberVO(Integer.parseInt(empno), auth, dvo.getDeptno(), id, password);
        evo.setMvo(mvo);


 		
 		int cnt=this.updateEmp(evo);
 		if(cnt>0) {
 			JOptionPane.showMessageDialog(change_emp.this, "emp저장완료!");
 		}
 		
 		
 		int cnt2=this.updateMember(mvo);
 		if(cnt2>0) {
 			JOptionPane.showMessageDialog(change_emp.this, "member저장완료!");
 			}
    
 		
    }//GEN-LAST:event_D_change_emp_bt_saveActionPerformed

    private void D_change_emp_bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_bt_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_D_change_emp_bt_cancelActionPerformed

    private void D_change_emp_tf_enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_tf_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_change_emp_tf_enameActionPerformed

    private void D_change_emp_cb_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_cb_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_change_emp_cb_bankActionPerformed

    private void D_change_emp_cb_employmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_cb_employmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_change_emp_cb_employmentActionPerformed

    private void D_change_emp_cb_obstacleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_cb_obstacleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_change_emp_cb_obstacleActionPerformed

    private void D_change_emp_cb_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_cb_leaveActionPerformed
        
    }//GEN-LAST:event_D_change_emp_cb_leaveActionPerformed

    private void D_change_emp_cb_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_change_emp_cb_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_change_emp_cb_genderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                change_emp dialog = new change_emp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D_change_emp_bt_cancel;
    private javax.swing.JButton D_change_emp_bt_save;
    private javax.swing.JComboBox<String> D_change_emp_cb_auth;
    private javax.swing.JComboBox<String> D_change_emp_cb_bank;
    private javax.swing.JComboBox<String> D_change_emp_cb_employment;
    private javax.swing.JComboBox<String> D_change_emp_cb_gender;
    private javax.swing.JCheckBox D_change_emp_cb_leave;
    private javax.swing.JComboBox<String> D_change_emp_cb_obstacle;
    private javax.swing.JComboBox<String> D_change_emp_cb_position;
    private javax.swing.JComboBox<String> D_change_emp_cb_venter;
    private javax.swing.JPanel D_change_emp_jp;
    private javax.swing.JLabel D_change_emp_lb_account;
    private javax.swing.JLabel D_change_emp_lb_address;
    private javax.swing.JLabel D_change_emp_lb_auth;
    private javax.swing.JLabel D_change_emp_lb_bank;
    private javax.swing.JLabel D_change_emp_lb_birth;
    private javax.swing.JLabel D_change_emp_lb_company;
    private javax.swing.JLabel D_change_emp_lb_dept;
    private javax.swing.JLabel D_change_emp_lb_employment;
    private javax.swing.JLabel D_change_emp_lb_empno;
    private javax.swing.JLabel D_change_emp_lb_ename;
    private javax.swing.JLabel D_change_emp_lb_gender;
    private javax.swing.JLabel D_change_emp_lb_hiredate;
    private javax.swing.JLabel D_change_emp_lb_hobby;
    private javax.swing.JLabel D_change_emp_lb_id;
    private javax.swing.JLabel D_change_emp_lb_job;
    private javax.swing.JLabel D_change_emp_lb_obstacle;
    private javax.swing.JLabel D_change_emp_lb_password;
    private javax.swing.JLabel D_change_emp_lb_phone;
    private javax.swing.JLabel D_change_emp_lb_position;
    private javax.swing.JLabel D_change_emp_lb_speciality;
    private javax.swing.JLabel D_change_emp_lb_title;
    private javax.swing.JLabel D_change_emp_lb_title2;
    private javax.swing.JLabel D_change_emp_lb_venter;
    private javax.swing.JTextField D_change_emp_tf_account;
    private javax.swing.JTextField D_change_emp_tf_add;
    private javax.swing.JTextField D_change_emp_tf_birth;
    private javax.swing.JTextField D_change_emp_tf_company;
    private javax.swing.JTextField D_change_emp_tf_empno;
    private javax.swing.JTextField D_change_emp_tf_ename;
    private javax.swing.JTextField D_change_emp_tf_hiredate;
    private javax.swing.JTextField D_change_emp_tf_hobby;
    private javax.swing.JTextField D_change_emp_tf_id;
    private javax.swing.JTextField D_change_emp_tf_job;
    private javax.swing.JTextField D_change_emp_tf_password;
    private javax.swing.JTextField D_change_emp_tf_phone;
    private javax.swing.JTextField D_change_emp_tf_speciality;
    private javax.swing.JSeparator D_change_js_line1;
    private javax.swing.JSeparator D_change_js_line2;
    private javax.swing.JComboBox<String> D_change_emp_cb_dept;
    // End of variables declaration//GEN-END:variables
}