/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialog;

import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.SqlSession;

import factory.Factory;
import view.C_card1;
import vo.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author a
 */
public class Detail_emp extends javax.swing.JDialog {
	EmpVO vo;
	

    /**
     * Creates new form Change_emp2
     * @wbp.parser.constructor
     */
	

	public Detail_emp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Detail_emp(EmpVO vo) {
    	this.vo = vo;
		SqlSession ss =Factory.getFactory().openSession();
		
		Map<String, String> map = new HashMap<>();
		/*map.put("deptno",vo.getDeptno());
		*/
		map.put("empno",String.valueOf(vo.getEmpno()));
		
		vo = ss.selectOne("emp.getDept", map);
		
		EmpVO mvo = ss.selectOne("emp.getMember", map);
		
		Map<String, String> map2 = new HashMap<>();
		map2.put("a_cate",String.valueOf(mvo.getMvo().getA_cate()));
		AuthorityVO avo = ss.selectOne("auth.allAuth", map2);

		initComponents();
		
		String empno = String.valueOf(vo.getEmpno());
		D_detail_emp_tf_empno.setText(empno);
		D_detail_emp_tf_company.setText(vo.getBelong());
		D_detail_emp_tf_id.setText(mvo.getMvo().getId());
		D_detail_emp_tf_ename.setText(vo.getEname());
		D_detail_emp_tf_password.setText(mvo.getMvo().getPw());
		D_detail_emp_tf_dept.setText(vo.getDvo().getDname());
		D_detail_emp_tf_position.setText(vo.getPosition());
		D_detail_emp_tf_d_number.setText(vo.getDvo().getD_number());
		D_detail_emp_tf_auth.setText(avo.getA_name());
		D_detail_emp_tf_phone.setText(vo.getPhone());
		D_detail_emp_tf_birth.setText(vo.getBirth());
		D_detail_emp_tf_job.setText(vo.getJob());
		String hireDateStr = vo.getHiredate().toString();
		int indexOfSpace = hireDateStr.indexOf(' ');
		String formattedHireDate = hireDateStr.substring(0, indexOfSpace);
		D_detail_emp_tf_hiredate.setText(formattedHireDate);
		D_detail_emp_tf_hobby.setText(vo.getHobby());
		D_detail_emp_tf_speciality.setText(vo.getSpecialty());
		D_detail_emp_tf_add.setText(vo.getAddress());
		D_detail_emp_tf_account.setText(vo.getAccount_number());
		D_detail_emp_cb_bank.setSelectedItem(vo.getBank_info());
		D_detail_emp_cb_employment.setSelectedItem(vo.getEmployment());
		if (vo.getVerterans() == 0) {
			D_detail_emp_cb_venter.setSelectedIndex(1);
	    }else if (vo.getVerterans() == 1) {
	    	D_detail_emp_cb_venter.setSelectedIndex(0);  
	    }
		if (vo.getObstacle() == 0) {
			D_detail_emp_cb_obstacle.setSelectedIndex(1);
	    }else if (vo.getVerterans() == 1) {
	    	D_detail_emp_cb_obstacle.setSelectedIndex(0);  
	    }
		
		if (vo.getJoin_status().equals("0")){
			D_detail_emp_tf_state.setText("재직중");
	    }else if (vo.getJoin_status().equals("1")) {
	    	String fireDateStr = vo.getFire_date().toString();
			int indexOfSpace2 = fireDateStr.indexOf(' ');
			String formattedFireDate = fireDateStr .substring(0, indexOfSpace2);
	    	D_detail_emp_tf_state.setText("퇴사"+" / "+"퇴사일:"+formattedFireDate);  
	    }
		
		
		D_detail_emp_tf_empno.setEditable(false);
		D_detail_emp_tf_company.setEditable(false);
		D_detail_emp_ta_sp.setEditable(false);
		D_detail_emp_tf_empno.setEditable(false);
		D_detail_emp_tf_company.setEditable(false);
		D_detail_emp_tf_id.setEditable(false);
		D_detail_emp_tf_ename.setEditable(false);
		D_detail_emp_tf_password.setEditable(false);
		D_detail_emp_tf_dept.setEditable(false);
		D_detail_emp_tf_position.setEditable(false);
		D_detail_emp_tf_d_number.setEditable(false);
		D_detail_emp_tf_auth.setEditable(false);
		D_detail_emp_tf_phone.setEditable(false);
		D_detail_emp_tf_birth.setEditable(false);
		D_detail_emp_tf_job.setEditable(false);
		D_detail_emp_cb_employment.setEnabled(false);
		D_detail_emp_tf_hiredate.setEditable(false);
		D_detail_emp_cb_venter.setEnabled(false);
		D_detail_emp_cb_obstacle.setEnabled(false);
		D_detail_emp_tf_hobby.setEditable(false);
		D_detail_emp_tf_speciality.setEditable(false);
		D_detail_emp_tf_add.setEditable(false);
		D_detail_emp_tf_state.setEditable(false);
		D_detail_emp_tf_account.setEditable(false);
		D_detail_emp_cb_bank.setEnabled(false);

		
		this.setVisible(true);
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_detail_emp_jp = new javax.swing.JPanel();
        D_detail_emp_lb_title = new javax.swing.JLabel();
        D_detail_js_line1 = new javax.swing.JSeparator();
        D_detail_emp_lb_ename = new javax.swing.JLabel();
        D_detail_emp_lb_empno = new javax.swing.JLabel();
        D_detail_emp_lb_employment = new javax.swing.JLabel();
        D_detail_emp_lb_auth = new javax.swing.JLabel();
        D_detail_js_line2 = new javax.swing.JSeparator();
        D_detail_emp_lb_title2 = new javax.swing.JLabel();
        D_detail_emp_lb_account = new javax.swing.JLabel();
        D_detail_emp_tf_empno = new javax.swing.JTextField();
        D_detail_emp_tf_id = new javax.swing.JTextField();
        D_detail_emp_tf_auth = new javax.swing.JTextField();
        D_detail_emp_tf_password = new javax.swing.JTextField();
        D_detail_emp_tf_account = new javax.swing.JTextField();
        D_detail_emp_bt_change = new javax.swing.JButton();
        D_detail_emp_lb_id = new javax.swing.JLabel();
        D_detail_emp_lb_dept = new javax.swing.JLabel();
        D_detail_emp_lb_job = new javax.swing.JLabel();
        D_detail_emp_tf_job = new javax.swing.JTextField();
        D_detail_emp_tf_dept = new javax.swing.JTextField();
        D_detail_emp_tf_ename = new javax.swing.JTextField();
        D_detail_emp_lb_bank = new javax.swing.JLabel();
        D_detail_emp_lb_password = new javax.swing.JLabel();
        D_detail_emp_lb_d_number = new javax.swing.JLabel();
        D_detail_emp_tf_d_number = new javax.swing.JTextField();
        D_detail_emp_lb_position = new javax.swing.JLabel();
        D_detail_emp_tf_position = new javax.swing.JTextField();
        D_detail_emp_lb_phone = new javax.swing.JLabel();
        D_detail_emp_tf_phone = new javax.swing.JTextField();
        D_detail_emp_lb_birth = new javax.swing.JLabel();
        D_detail_emp_lb_hiredate = new javax.swing.JLabel();
        D_detail_emp_tf_hiredate = new javax.swing.JTextField();
        D_detail_emp_lb_hobby = new javax.swing.JLabel();
        D_detail_emp_tf_hobby = new javax.swing.JTextField();
        D_detail_emp_lb_speciality = new javax.swing.JLabel();
        D_detail_emp_tf_speciality = new javax.swing.JTextField();
        D_detail_emp_lb_venter = new javax.swing.JLabel();
        D_detail_emp_lb_obstacle = new javax.swing.JLabel();
        D_detail_emp_tf_birth = new javax.swing.JTextField();
        D_detail_emp_lb_company = new javax.swing.JLabel();
        D_detail_emp_tf_company = new javax.swing.JTextField();
        D_detail_emp_cb_bank = new javax.swing.JComboBox<>();
        D_detail_emp_cb_employment = new javax.swing.JComboBox<>();
        D_detail_emp_cb_obstacle = new javax.swing.JComboBox<>();
        D_detail_emp_cb_venter = new javax.swing.JComboBox<>();
        D_detail_emp_lb_address = new javax.swing.JLabel();
        D_detail_emp_tf_add = new javax.swing.JTextField();
        D_detail_emp_lb_img = new javax.swing.JLabel();
        D_detail_emp_js_sp = new javax.swing.JScrollPane();
        D_detail_emp_ta_sp = new javax.swing.JTextArea();
        D_detail_emp_lb_sp1 = new javax.swing.JLabel();
        D_detail_emp_lb_state = new javax.swing.JLabel();
        D_detail_emp_tf_state = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));

        D_detail_emp_jp.setBackground(new java.awt.Color(255, 255, 255));
        D_detail_emp_jp.setMaximumSize(new java.awt.Dimension(800, 550));

        D_detail_emp_lb_title.setFont(new java.awt.Font("맑은 고딕", 1, 22)); // NOI18N
        D_detail_emp_lb_title.setText("구성원 상세");

        D_detail_emp_lb_ename.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_ename.setText("이름*");

        D_detail_emp_lb_empno.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_empno.setText("사번*");

        D_detail_emp_lb_employment.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_employment.setText("직원구분");

        D_detail_emp_lb_auth.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_auth.setText("권한");

        D_detail_emp_lb_title2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        D_detail_emp_lb_title2.setForeground(new java.awt.Color(51, 153, 255));
        D_detail_emp_lb_title2.setText("계좌정보");

        D_detail_emp_lb_account.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_account.setText("계좌번호");

        D_detail_emp_tf_empno.setText("jTextField1");
        D_detail_emp_tf_empno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_tf_empnoActionPerformed(evt);
            }
        });

        D_detail_emp_tf_id.setText("jTextField1");

        D_detail_emp_tf_auth.setText("jTextField1");

        D_detail_emp_tf_password.setText("jTextField1");

        D_detail_emp_tf_account.setText("jTextField1");
        D_detail_emp_tf_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_tf_accountActionPerformed(evt);
            }
        });

        D_detail_emp_bt_change.setBackground(new java.awt.Color(0, 153, 255));
        D_detail_emp_bt_change.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_bt_change.setForeground(new java.awt.Color(255, 255, 255));
        D_detail_emp_bt_change.setText("수정");
        D_detail_emp_bt_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_bt_changeActionPerformed(evt);
            }
        });

        D_detail_emp_lb_id.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_id.setText("아이디*");

        D_detail_emp_lb_dept.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_dept.setText("부서명");

        D_detail_emp_lb_job.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_job.setText("직종");

        D_detail_emp_tf_job.setText("jTextField1");

        D_detail_emp_tf_dept.setText("jTextField1");

        D_detail_emp_tf_ename.setText("jTextField1");
       

        D_detail_emp_lb_bank.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_bank.setText("은행정보");

        D_detail_emp_lb_password.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_password.setText("비밀번호");

        D_detail_emp_lb_d_number.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_d_number.setText("내선번호");

        D_detail_emp_tf_d_number.setText("jTextField1");

        D_detail_emp_lb_position.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_position.setText("직책");

        D_detail_emp_tf_position.setText("jTextField1");

        D_detail_emp_lb_phone.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_phone.setText("휴대폰번호");

        D_detail_emp_tf_phone.setText("jTextField1");

        D_detail_emp_lb_birth.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_birth.setText("생년월일");

        D_detail_emp_lb_hiredate.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_hiredate.setText("입사일");

        D_detail_emp_tf_hiredate.setText("jTextField1");

        D_detail_emp_lb_hobby.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_hobby.setText("취미");

        D_detail_emp_tf_hobby.setText("jTextField1");

        D_detail_emp_lb_speciality.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_speciality.setText("특기");

        D_detail_emp_tf_speciality.setText("jTextField1");

        D_detail_emp_lb_venter.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_venter.setText("보훈여부");

        D_detail_emp_lb_obstacle.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_obstacle.setText("장애여부");

        D_detail_emp_tf_birth.setText("jTextField1");

        D_detail_emp_lb_company.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_company.setText("소속");

        D_detail_emp_tf_company.setText("jTextField1");

        D_detail_emp_cb_bank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KEB하나은행", "SC제일은행", "국민은행", "신한은행", "외환은행", "우리은행", "농협", "한국시티은행", "카카오뱅크", "토스", "기업은행", "신협" }));
        D_detail_emp_cb_bank.setToolTipText("");
        D_detail_emp_cb_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_cb_bankActionPerformed(evt);
            }
        });

        D_detail_emp_cb_employment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "정규직", "비정규직" }));
        D_detail_emp_cb_employment.setToolTipText("");
        D_detail_emp_cb_employment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_cb_employmentActionPerformed(evt);
            }
        });

        D_detail_emp_cb_obstacle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "N" }));
        D_detail_emp_cb_obstacle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_cb_obstacleActionPerformed(evt);
            }
        });

        D_detail_emp_cb_venter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "N" }));
        D_detail_emp_cb_venter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_cb_venterActionPerformed(evt);
            }
        });

        D_detail_emp_lb_address.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        D_detail_emp_lb_address.setText("주소");

        D_detail_emp_tf_add.setText("jTextField1");

        D_detail_emp_lb_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_detail_emp_lb_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile.jpg"))); // NOI18N
        D_detail_emp_lb_img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        D_detail_emp_ta_sp.setColumns(20);
        D_detail_emp_ta_sp.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        D_detail_emp_ta_sp.setRows(5);
        D_detail_emp_ta_sp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        D_detail_emp_ta_sp.setFocusCycleRoot(true);
        D_detail_emp_ta_sp.setFocusable(false);
        D_detail_emp_js_sp.setViewportView(D_detail_emp_ta_sp);

        D_detail_emp_lb_sp1.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        D_detail_emp_lb_sp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_detail_emp_lb_sp1.setText("자기소개");

        D_detail_emp_lb_state.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_detail_emp_lb_state.setText("재직상태");

        D_detail_emp_tf_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_detail_emp_tf_stateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout D_detail_emp_jpLayout = new javax.swing.GroupLayout(D_detail_emp_jp);
        D_detail_emp_jpLayout.setHorizontalGroup(
        	D_detail_emp_jpLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        			.addGap(38)
        			.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(D_detail_js_line1, GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        						.addComponent(D_detail_emp_lb_title)
        						.addComponent(D_detail_js_line2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(0, 56, Short.MAX_VALUE))
        				.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        					.addGap(48)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(D_detail_emp_lb_img, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        						.addComponent(D_detail_emp_js_sp, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
        						.addComponent(D_detail_emp_lb_sp1, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE))
        					.addGap(90)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(D_detail_emp_lb_empno)
        						.addComponent(D_detail_emp_lb_auth)
        						.addComponent(D_detail_emp_lb_id)
        						.addComponent(D_detail_emp_lb_password)
        						.addComponent(D_detail_emp_lb_position)
        						.addComponent(D_detail_emp_lb_employment)
        						.addComponent(D_detail_emp_lb_hobby)
        						.addComponent(D_detail_emp_lb_venter)
        						.addComponent(D_detail_emp_lb_birth)
        						.addComponent(D_detail_emp_lb_address)
        						.addComponent(D_detail_emp_lb_state, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
        					.addGap(87)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.TRAILING)
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(D_detail_emp_tf_auth, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_password, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_id, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_empno, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_birth, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_position, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
        									.addComponent(D_detail_emp_cb_employment, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE))
        								.addComponent(D_detail_emp_cb_venter, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        								.addComponent(D_detail_emp_tf_hobby, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE))
        							.addGap(90)
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(D_detail_emp_lb_d_number)
        										.addComponent(D_detail_emp_lb_hiredate)
        										.addComponent(D_detail_emp_lb_dept)
        										.addComponent(D_detail_emp_lb_job)
        										.addComponent(D_detail_emp_lb_ename)
        										.addComponent(D_detail_emp_lb_phone)
        										.addComponent(D_detail_emp_lb_company))
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(D_detail_emp_tf_hiredate, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_job, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_phone, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_d_number, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_dept, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_ename, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_tf_company, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)))
        								.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(D_detail_emp_lb_obstacle)
        										.addComponent(D_detail_emp_lb_speciality))
        									.addGap(18)
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(D_detail_emp_tf_speciality, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        										.addComponent(D_detail_emp_cb_obstacle, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.RELATED, 1, Short.MAX_VALUE)))
        							.addGap(141))
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(D_detail_emp_tf_add, GroupLayout.PREFERRED_SIZE, 430, GroupLayout.PREFERRED_SIZE)
        								.addComponent(D_detail_emp_tf_state, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))
        							.addContainerGap(51, Short.MAX_VALUE))))))
        		.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        			.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        					.addContainerGap(779, Short.MAX_VALUE)
        					.addComponent(D_detail_emp_bt_change, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        				.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        					.addGap(48)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addComponent(D_detail_emp_lb_title2)
        							.addGap(373))
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addComponent(D_detail_emp_lb_account)
        							.addGap(18)
        							.addComponent(D_detail_emp_tf_account, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE)
        							.addGap(79)
        							.addComponent(D_detail_emp_lb_bank)))
        					.addGap(18)
        					.addComponent(D_detail_emp_cb_bank, 0, 359, Short.MAX_VALUE)))
        			.addGap(141))
        );
        D_detail_emp_jpLayout.setVerticalGroup(
        	D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        			.addGap(14)
        			.addComponent(D_detail_emp_lb_title)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(D_detail_js_line1, GroupLayout.PREFERRED_SIZE, 4, GroupLayout.PREFERRED_SIZE)
        			.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(D_detail_emp_tf_empno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(D_detail_emp_lb_empno)
        						.addComponent(D_detail_emp_tf_company, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(D_detail_emp_lb_company))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(D_detail_emp_tf_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(D_detail_emp_tf_ename, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(D_detail_emp_lb_ename))
        						.addComponent(D_detail_emp_lb_id, Alignment.TRAILING))
        					.addGap(0, 268, Short.MAX_VALUE))
        				.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        									.addGap(70)
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        										.addComponent(D_detail_emp_lb_dept)
        										.addComponent(D_detail_emp_tf_dept, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        										.addComponent(D_detail_emp_lb_d_number)
        										.addComponent(D_detail_emp_tf_d_number, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        								.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        									.addGap(79, 83, Short.MAX_VALUE)
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        										.addComponent(D_detail_emp_lb_password)
        										.addComponent(D_detail_emp_tf_password, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        										.addComponent(D_detail_emp_lb_position)
        										.addComponent(D_detail_emp_tf_position, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(D_detail_emp_tf_auth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(D_detail_emp_lb_auth)
        								.addComponent(D_detail_emp_lb_phone)
        								.addComponent(D_detail_emp_tf_phone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addGap(28)
        							.addComponent(D_detail_emp_lb_img, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(D_detail_emp_tf_birth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(D_detail_emp_lb_birth)
        								.addComponent(D_detail_emp_lb_job)
        								.addComponent(D_detail_emp_tf_job, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(D_detail_emp_lb_employment)
        								.addComponent(D_detail_emp_cb_employment, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(D_detail_emp_lb_hiredate)
        								.addComponent(D_detail_emp_tf_hiredate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(D_detail_emp_lb_venter)
        								.addComponent(D_detail_emp_cb_venter, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(D_detail_emp_lb_obstacle)
        								.addComponent(D_detail_emp_cb_obstacle, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(D_detail_emp_lb_hobby)
        								.addComponent(D_detail_emp_tf_hobby, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        								.addComponent(D_detail_emp_lb_speciality)
        								.addComponent(D_detail_emp_tf_speciality, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(D_detail_emp_lb_address)
        								.addComponent(D_detail_emp_tf_add, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        							.addComponent(D_detail_emp_lb_sp1)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(D_detail_emp_js_sp, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)))))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(D_detail_emp_jpLayout.createSequentialGroup()
        					.addComponent(D_detail_emp_lb_state, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        					.addGap(27)
        					.addComponent(D_detail_js_line2, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(D_detail_emp_lb_title2)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(D_detail_emp_jpLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(D_detail_emp_lb_account)
        						.addComponent(D_detail_emp_tf_account, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(D_detail_emp_lb_bank)
        						.addComponent(D_detail_emp_cb_bank, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addComponent(D_detail_emp_bt_change))
        				.addComponent(D_detail_emp_tf_state, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(14, Short.MAX_VALUE))
        );
        D_detail_emp_jp.setLayout(D_detail_emp_jpLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(D_detail_emp_jp, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(D_detail_emp_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_detail_emp_tf_empnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_tf_empnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_tf_empnoActionPerformed

    private void D_detail_emp_tf_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_tf_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_tf_accountActionPerformed

    private void D_detail_emp_bt_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_bt_changeActionPerformed
    	new change_emp(Detail_emp.this);
    	dispose();

    }//GEN-LAST:event_D_detail_emp_bt_changeActionPerformed

    private void D_detail_emp_tf_enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_tf_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_tf_enameActionPerformed

    private void D_detail_emp_cb_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_cb_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_cb_bankActionPerformed

    private void D_detail_emp_cb_employmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_cb_employmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_cb_employmentActionPerformed

    private void D_detail_emp_cb_obstacleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_cb_obstacleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_cb_obstacleActionPerformed

    private void D_detail_emp_tf_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_tf_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_tf_stateActionPerformed

    private void D_detail_emp_cb_venterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_detail_emp_cb_venterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_detail_emp_cb_venterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Detail_emp dialog = new Detail_emp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D_detail_emp_bt_change;
    public javax.swing.JComboBox<String> D_detail_emp_cb_bank;
    public javax.swing.JComboBox<String> D_detail_emp_cb_employment;
    public javax.swing.JComboBox<String> D_detail_emp_cb_obstacle;
    public javax.swing.JComboBox<String> D_detail_emp_cb_venter;
    private javax.swing.JPanel D_detail_emp_jp;
    private javax.swing.JScrollPane D_detail_emp_js_sp;
    private javax.swing.JLabel D_detail_emp_lb_account;
    private javax.swing.JLabel D_detail_emp_lb_address;
    private javax.swing.JLabel D_detail_emp_lb_auth;
    private javax.swing.JLabel D_detail_emp_lb_bank;
    private javax.swing.JLabel D_detail_emp_lb_birth;
    private javax.swing.JLabel D_detail_emp_lb_company;
    private javax.swing.JLabel D_detail_emp_lb_d_number;
    private javax.swing.JLabel D_detail_emp_lb_dept;
    private javax.swing.JLabel D_detail_emp_lb_employment;
    private javax.swing.JLabel D_detail_emp_lb_empno;
    private javax.swing.JLabel D_detail_emp_lb_ename;
    private javax.swing.JLabel D_detail_emp_lb_hiredate;
    private javax.swing.JLabel D_detail_emp_lb_hobby;
    private javax.swing.JLabel D_detail_emp_lb_id;
    private javax.swing.JLabel D_detail_emp_lb_img;
    private javax.swing.JLabel D_detail_emp_lb_job;
    private javax.swing.JLabel D_detail_emp_lb_obstacle;
    private javax.swing.JLabel D_detail_emp_lb_password;
    private javax.swing.JLabel D_detail_emp_lb_phone;
    private javax.swing.JLabel D_detail_emp_lb_position;
    private javax.swing.JLabel D_detail_emp_lb_sp1;
    private javax.swing.JLabel D_detail_emp_lb_speciality;
    private javax.swing.JLabel D_detail_emp_lb_state;
    private javax.swing.JLabel D_detail_emp_lb_title;
    private javax.swing.JLabel D_detail_emp_lb_title2;
    private javax.swing.JLabel D_detail_emp_lb_venter;
    private javax.swing.JTextArea D_detail_emp_ta_sp;
    public javax.swing.JTextField D_detail_emp_tf_account;
    public javax.swing.JTextField D_detail_emp_tf_add;
    public javax.swing.JTextField D_detail_emp_tf_auth;
    public javax.swing.JTextField D_detail_emp_tf_birth;
    public javax.swing.JTextField D_detail_emp_tf_company;
    public javax.swing.JTextField D_detail_emp_tf_d_number;
    public javax.swing.JTextField D_detail_emp_tf_dept;
    public javax.swing.JTextField D_detail_emp_tf_empno;
    public javax.swing.JTextField D_detail_emp_tf_ename;
    public javax.swing.JTextField D_detail_emp_tf_hiredate;
    public javax.swing.JTextField D_detail_emp_tf_hobby;
    public javax.swing.JTextField D_detail_emp_tf_id;
    public javax.swing.JTextField D_detail_emp_tf_job;
    public javax.swing.JTextField D_detail_emp_tf_password;
    public javax.swing.JTextField D_detail_emp_tf_phone;
    public javax.swing.JTextField D_detail_emp_tf_position;
    public javax.swing.JTextField D_detail_emp_tf_speciality;
    public javax.swing.JTextField D_detail_emp_tf_state;
    public javax.swing.JSeparator D_detail_js_line1;
    public javax.swing.JSeparator D_detail_js_line2;
    // End of variables declaration//GEN-END:variables
}
