/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author 20191
 */
public class Background extends javax.swing.JPanel {

	public Background() {
		initComponents();
        checkPosition();
	}
	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_emp = new javax.swing.JPanel();
        menu_card = new javax.swing.JPanel();
        content_card = new javax.swing.JPanel();

        //setName(""); // NOI18N

        background_emp.setLayout(new java.awt.BorderLayout());

        menu_card.setBackground(new java.awt.Color(255, 255, 255));
        menu_card.setPreferredSize(new java.awt.Dimension(200, 800));
        menu_card.setLayout(new java.awt.CardLayout());
        background_emp.add(menu_card, java.awt.BorderLayout.LINE_START);

        content_card.setName("content_card"); // NOI18N
        content_card.setPreferredSize(new java.awt.Dimension(1100, 800));
        content_card.setLayout(new java.awt.CardLayout());
        background_emp.add(content_card, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        
    }// </editor-fold>//GEN-END:initComponents
        
    void checkPosition() {
    	//임시 로그인
        if(Login.mvo.getA_cate()==0) { //사원 일 때
        	Menu_emp emp = new Menu_emp();
        	menu_card.add(emp, "Menu_emp");
        	CardLayout card = (CardLayout)menu_card.getLayout();
        	card.show(menu_card, "Menu_emp");
        	
        	A_card1 card1 = new A_card1();
        	content_card.add(card1, "A_card1");
        	CardLayout card2 = (CardLayout)content_card.getLayout();
        	card2.show(content_card, "A_card1");
        }
        else if(Login.mvo.getA_cate()==1) { //팀장일 때
        	Menu_leader leader = new Menu_leader();
        	menu_card.add(leader, "Menu_leader");
        	CardLayout card = (CardLayout)menu_card.getLayout();
        	card.show(menu_card, "Menu_leader");
        	
        	A_card1 card1 = new A_card1();
        	content_card.add(card1, "A_card1");
        	CardLayout card2 = (CardLayout)content_card.getLayout();
        	card2.show(content_card, "A_card1");
        }
        else if(Login.mvo.getA_cate()==2) { //관리자일 때
        	Menu_manager manager = new Menu_manager();
        	menu_card.add(manager, "Menu_manager");
        	CardLayout card = (CardLayout)menu_card.getLayout();
        	card.show(menu_card, "Menu_manager");
        	
        	C_card1 card1 = new C_card1();
        	content_card.add(card1, "C_card1");
        	CardLayout card2 = (CardLayout)content_card.getLayout();
        	card2.show(content_card, "C_card1");
        }
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background_emp;
    private javax.swing.JPanel menu_card;
    static javax.swing.JPanel content_card; //*****static 중요******
    // End of variables declaration//GEN-END:variables
}
