/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import org.apache.ibatis.session.SqlSession;

import dialog.Detail_emp;
import dialog.Insert_emp;
import factory.Factory;
import vo.*;

/**
 *
 * @author 20191
 */
public class C_card1 extends javax.swing.JPanel {
	List<EmpVO> list;
    /**
     * Creates new form C_card1
     */
    public C_card1() {
        initComponents();
        settable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        C_card1 = new javax.swing.JPanel();
        C_1_Panel1 = new javax.swing.JPanel();
        C_1_Panel2 = new javax.swing.JPanel();
        C_1_tf_personnel = new javax.swing.JTextField();
        C_1_Label1 = new javax.swing.JLabel();
        C_1_Label2 = new javax.swing.JLabel();
        C_1_Separator = new javax.swing.JSeparator();
        C_1_bt_regist = new javax.swing.JButton();
        C_1_scrollPane = new javax.swing.JScrollPane();
        C_1_tb_tableMem = new javax.swing.JTable();
        commanange7 = new javax.swing.JPanel();
        B_3_Label7 = new javax.swing.JLabel();
        C_1_tb_tableMem.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				int row = C_1_tb_tableMem.getSelectedRow();

				//멤버변수인 list에서 row번째에 있는  DataVO를 얻어낸다.
				EmpVO vo = list.get(row);
				Detail_emp dd = new Detail_emp(vo);

			}
        });
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));

        C_card1.setMaximumSize(new java.awt.Dimension(1100, 700));
        C_card1.setMinimumSize(new java.awt.Dimension(1100, 700));
        C_card1.setPreferredSize(new java.awt.Dimension(1100, 700));

        C_1_Panel1.setBackground(new java.awt.Color(204, 204, 204));
        C_1_Panel1.setMaximumSize(new java.awt.Dimension(1100, 700));
        C_1_Panel1.setMinimumSize(new java.awt.Dimension(1100, 700));
        C_1_Panel1.setPreferredSize(new java.awt.Dimension(1100, 700));

        C_1_Panel2.setBackground(new java.awt.Color(51, 51, 51));

        C_1_tf_personnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_1_tf_personnelActionPerformed(evt);
            }
        });

        C_1_Label1.setForeground(new java.awt.Color(255, 255, 255));
        C_1_Label1.setText("총 인원");

        javax.swing.GroupLayout C_1_Panel2Layout = new javax.swing.GroupLayout(C_1_Panel2);
        C_1_Panel2.setLayout(C_1_Panel2Layout);
        C_1_Panel2Layout.setHorizontalGroup(
            C_1_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(C_1_Panel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(C_1_Label1)
                .addGap(27, 27, 27)
                .addComponent(C_1_tf_personnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(940, Short.MAX_VALUE))
        );
        C_1_Panel2Layout.setVerticalGroup(
            C_1_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, C_1_Panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(C_1_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_1_tf_personnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_1_Label1))
                .addGap(14, 14, 14))
        );

        C_1_Separator.setBackground(new java.awt.Color(255, 255, 255));
        C_1_Separator.setForeground(new java.awt.Color(153, 153, 153));

        C_1_bt_regist.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        C_1_bt_regist.setText("등록");
        C_1_bt_regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_1_bt_registActionPerformed(evt);
            }
        });
        /*
        C_1_tb_tableMem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, new String [] {"이름", "부서", "내선번호", "전화번호"}
        ));
        */
        C_1_scrollPane.setViewportView(C_1_tb_tableMem);

        commanange7.setBackground(new java.awt.Color(0, 0, 0));

        B_3_Label7.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        B_3_Label7.setForeground(new java.awt.Color(255, 255, 255));
        B_3_Label7.setText("구성원 관리");

        javax.swing.GroupLayout commanange7Layout = new javax.swing.GroupLayout(commanange7);
        commanange7.setLayout(commanange7Layout);
        commanange7Layout.setHorizontalGroup(
            commanange7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commanange7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_3_Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        commanange7Layout.setVerticalGroup(
            commanange7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commanange7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_3_Label7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout C_1_Panel1Layout = new javax.swing.GroupLayout(C_1_Panel1);
        C_1_Panel1.setLayout(C_1_Panel1Layout);
        C_1_Panel1Layout.setHorizontalGroup(
            C_1_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(C_1_Panel1Layout.createSequentialGroup()
                .addGroup(C_1_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_1_Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(C_1_Panel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(C_1_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(C_1_bt_regist)
                            .addComponent(C_1_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_1_Label2))
            .addGroup(C_1_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C_1_Separator)
                .addContainerGap())
            .addComponent(commanange7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        C_1_Panel1Layout.setVerticalGroup(
            C_1_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(C_1_Panel1Layout.createSequentialGroup()
                .addGroup(C_1_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(C_1_Panel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(C_1_Label2))
                    .addGroup(C_1_Panel1Layout.createSequentialGroup()
                        .addComponent(commanange7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C_1_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C_1_Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(C_1_scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(C_1_bt_regist, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout C_card1Layout = new javax.swing.GroupLayout(C_card1);
        C_card1.setLayout(C_card1Layout);
        C_card1Layout.setHorizontalGroup(
            C_card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C_1_Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        C_card1Layout.setVerticalGroup(
            C_card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C_1_Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(C_card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(C_card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void C_1_tf_personnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_1_tf_personnelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_1_tf_personnelActionPerformed

    private void C_1_bt_registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_1_bt_registActionPerformed
    	new Insert_emp(C_card1.this);
    }//GEN-LAST:event_C_1_bt_registActionPerformed

    public void settable() {
    	
		SqlSession ss =Factory.getFactory().openSession();
		
		String[] c_name = {"이름","부서","내선번호","전화번호"};
		list = ss.selectList("emp.getDept");
		String[][] data = new String[list.size()][c_name.length];

		for (int i = 0; i < list.size(); i++) {
			EmpVO evo = list.get(i);
			DeptVO dvo = evo.getDvo();

		    data[i][0] = evo.getEname(); 
		    data[i][1] = dvo.getDname(); 
		    data[i][2] = dvo.getD_number();
		    data[i][3] = evo.getPhone(); 
		}

        DefaultTableModel model = new DefaultTableModel(data, c_name);
		C_1_tb_tableMem.setModel(model);
        DefaultRowSorter sorter = new TableRowSorter<DefaultTableModel>(model);
        C_1_tb_tableMem.setRowSorter(sorter);
		
		int rowCount = C_1_tb_tableMem.getRowCount();
		C_1_tf_personnel.setText(String.valueOf(rowCount));
		
		if(ss != null)
			ss.close();
    }
    
    public int addEmp(EmpVO vo) {
		SqlSession ss = Factory.getFactory().openSession();
		
		int cnt = ss.insert("emp.add", vo);
		
		if(cnt > 0)
			ss.commit();
		else
			ss.rollback();

		if(ss != null)
			ss.close();
		
		return cnt;
	}
    
    public int addMember(MemberVO mvo) {
		SqlSession ss = Factory.getFactory().openSession();
		
		int cnt = ss.insert("member.add", mvo);
		
		if(cnt > 0)
			ss.commit();
		else
			ss.rollback();
		
		if(ss != null)
			ss.close();
		
		return cnt;
	}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_3_Label7;
    private javax.swing.JLabel C_1_Label1;
    private javax.swing.JLabel C_1_Label2;
    private javax.swing.JPanel C_1_Panel1;
    private javax.swing.JPanel C_1_Panel2;
    private javax.swing.JSeparator C_1_Separator;
    private javax.swing.JButton C_1_bt_regist;
    private javax.swing.JScrollPane C_1_scrollPane;
    private javax.swing.JTable C_1_tb_tableMem;
    private javax.swing.JTextField C_1_tf_personnel;
    private javax.swing.JPanel C_card1;
    private javax.swing.JPanel commanange7;
    // End of variables declaration//GEN-END:variables
}
