/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.*;
import org.apache.ibatis.session.SqlSession;


import vo.MemberVO;
import factory.Factory;
/**
 *
 * @author 20191
 */
public class Login extends javax.swing.JFrame {
	
    public Login() {
        initComponents();
        setVisible(true);
        setBounds(100, 30, 1320, 740); //창 크기가 다 안 떠서 임시로 이렇게 수정
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        login_card = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        login_background = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        login_view = new javax.swing.JPanel();
        lb_login_title = new javax.swing.JLabel();
        lb_login_id = new javax.swing.JLabel();
        tf_login_id = new javax.swing.JTextField();
        lb_login_pw = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        tf_login_pw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));

        login_card.setMaximumSize(new java.awt.Dimension(1300, 700));
        login_card.setName(""); // NOI18N
        login_card.setPreferredSize(new java.awt.Dimension(1300, 700));
        login_card.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(233, 240, 248));
        login.setMaximumSize(new java.awt.Dimension(1300, 700));
        login.setMinimumSize(new java.awt.Dimension(1300, 700));
        login.setVerifyInputWhenFocusTarget(false);

        login_background.setBackground(new java.awt.Color(52, 73, 102));
        login_background.setMaximumSize(new java.awt.Dimension(800, 400));
        login_background.setMinimumSize(new java.awt.Dimension(800, 400));

        lb_title.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("사원 관리 프로그램");
        lb_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        login_view.setBackground(new java.awt.Color(87, 144, 171));
        login_view.setPreferredSize(new java.awt.Dimension(300, 300));

        lb_login_title.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lb_login_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_login_title.setText("LOG IN");
        lb_login_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_login_id.setFont(new java.awt.Font("맑은 고딕 Semilight", 1, 12)); // NOI18N
        lb_login_id.setText("ID");

        lb_login_pw.setFont(new java.awt.Font("맑은 고딕 Semilight", 1, 12)); // NOI18N
        lb_login_pw.setText("PW");

        bt_login.setBackground(new java.awt.Color(87, 144, 171));
        bt_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        bt_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 144, 171)));
        bt_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_viewLayout = new javax.swing.GroupLayout(login_view);
        login_view.setLayout(login_viewLayout);
        login_viewLayout.setHorizontalGroup(
            login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_viewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(login_viewLayout.createSequentialGroup()
                .addGroup(login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_viewLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_login_id)
                            .addComponent(tf_login_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(login_viewLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lb_login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(login_viewLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_login_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_login_pw))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        login_viewLayout.setVerticalGroup(
            login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_viewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lb_login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_login_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_login_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_login_pw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_login_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout login_backgroundLayout = new javax.swing.GroupLayout(login_background);
        login_background.setLayout(login_backgroundLayout);
        login_backgroundLayout.setHorizontalGroup(
            login_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_backgroundLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        login_backgroundLayout.setVerticalGroup(
            login_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_backgroundLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_backgroundLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(login_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(login_background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(login_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(148, 148, 148))
        );

        login_card.add(login, "login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
    	SqlSession ss = Factory.getFactory().openSession();
        
        MemberVO input = new MemberVO();
        input.setId(tf_login_id.getText());
        input.setPw(tf_login_pw.getText());
        
        mvo = ss.selectOne("login.checkLogin", input);
        // 로그인 과정
        CardLayout card = (CardLayout) login_card.getLayout();
        String selectedPanel = "";
        int position = 0;

        if (mvo != null && mvo.getA_cate() >= 0 && mvo.getA_cate() <= 2) {
            switch (mvo.getA_cate()) {
                case 0:
                    selectedPanel = "Menu_emp";
                    System.out.println("사원 로그인 성공");
                    position = 1;
                    break;
                case 1:
                    selectedPanel = "Menu_leader";
                    System.out.println("팀장 로그인 성공");
                    position = 2;
                    break;
                case 2:
                    selectedPanel = "Menu_manager";
                    System.out.println("관리자 로그인 성공");
                    position = 3;
                    break;
            }
            
            Background bg = new Background();
        	login_card.add(bg, "Background");
        	CardLayout card1 = (CardLayout)login_card.getLayout();
            card1.show(login_card, "Background");
            
        } else {
            JOptionPane.showMessageDialog(Login.this, "아이디와 비밀번호를 다시 확인하세요");
        }
    }
    
    public static void main(String args[]) {
    	new Login();
    }
    
    public static MemberVO mvo;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel lb_login_id;
    private javax.swing.JLabel lb_login_pw;
    private javax.swing.JLabel lb_login_title;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPanel login;
    private javax.swing.JPanel login_background;
    private javax.swing.JPanel login_view;
    private javax.swing.JTextField tf_login_id;
    private javax.swing.JPasswordField tf_login_pw;
    static javax.swing.JPanel login_card; //*********중요*********
    // End of variables declaration//GEN-END:variables
}
