/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.util.List;

import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import org.apache.ibatis.session.SqlSession;

import factory.Factory;
import vo.*;

/**
 *
 * @author 20191
 */
public class Menu_leader extends javax.swing.JPanel {

	List<FileVO> fileList;
	MemberVO member;
	List<WLogVO> list;
	JTable table;
	
    /**
     * Creates new form menu_leader
     */
    public Menu_leader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_leader = new javax.swing.JPanel();
        lb_leader_menu_title = new javax.swing.JLabel();
        lb_leader_menu1_main = new javax.swing.JLabel();
        lb_leader_menu2_log = new javax.swing.JLabel();
        lb_leader_menu3_attendance = new javax.swing.JLabel();
        lb_leader_menu4_file = new javax.swing.JLabel();
        lb_leader_menu5_view = new javax.swing.JLabel();
        lb_leader_menu6_deptlog = new javax.swing.JLabel();
        lb_leader_menu7_deptatt = new javax.swing.JLabel();
        lb_leader_menu8_deptvacation = new javax.swing.JLabel();
        lb_leader_menu9_deptemp = new javax.swing.JLabel();
        lb_leader_menu10_logout = new javax.swing.JLabel();
        EmptyBorder emptyBorder = new EmptyBorder(200, 10, 200, 10);

        setMaximumSize(new java.awt.Dimension(200, 700));
        setMinimumSize(new java.awt.Dimension(200, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 700));

        menu_leader.setBackground(new java.awt.Color(87, 144, 171));
        menu_leader.setMaximumSize(new java.awt.Dimension(200, 700));
        menu_leader.setMinimumSize(new java.awt.Dimension(200, 700));
        menu_leader.setPreferredSize(new java.awt.Dimension(200, 700));
        menu_leader.setLayout(new java.awt.GridLayout(11, 1));

        lb_leader_menu_title.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lb_leader_menu_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_leader_menu_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/title.png"))); // NOI18N
        lb_leader_menu_title.setText("메뉴");
        lb_leader_menu_title.setIconTextGap(10);
        menu_leader.add(lb_leader_menu_title);

        lb_leader_menu1_main.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu1_main.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu1_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mian.png"))); // NOI18N
        lb_leader_menu1_main.setBorder(emptyBorder);
        lb_leader_menu1_main.setText("메인화면");
        lb_leader_menu1_main.setIconTextGap(10);
        lb_leader_menu1_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu1_mainMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu1_main);

        lb_leader_menu2_log.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu2_log.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu2_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log.png"))); // NOI18N
        lb_leader_menu2_log.setBorder(emptyBorder);
        lb_leader_menu2_log.setText("업무일지 조회");
        lb_leader_menu2_log.setIconTextGap(10);
        lb_leader_menu2_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu2_logMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu2_log);

        lb_leader_menu3_attendance.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu3_attendance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu3_attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/attendance.png"))); // NOI18N
        lb_leader_menu3_attendance.setBorder(emptyBorder);
        lb_leader_menu3_attendance.setText("근태 관리");
        lb_leader_menu3_attendance.setIconTextGap(10);
        lb_leader_menu3_attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu3_attendanceMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu3_attendance);

        lb_leader_menu4_file.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu4_file.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu4_file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file.png"))); // NOI18N
        lb_leader_menu4_file.setBorder(emptyBorder);
        lb_leader_menu4_file.setText("문서함");
        lb_leader_menu4_file.setIconTextGap(10);
        lb_leader_menu4_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu4_fileMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu4_file);

        lb_leader_menu5_view.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu5_view.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu5_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view.png"))); // NOI18N
        lb_leader_menu5_view.setBorder(emptyBorder);
        lb_leader_menu5_view.setText("출퇴근 조회");
        lb_leader_menu5_view.setIconTextGap(10);
        lb_leader_menu5_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu5_viewMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu5_view);

        lb_leader_menu6_deptlog.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu6_deptlog.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu6_deptlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deptlog.png"))); // NOI18N
        lb_leader_menu6_deptlog.setBorder(emptyBorder);
        lb_leader_menu6_deptlog.setText("<html>부서 내<br>업무일지 조회<html>");
        lb_leader_menu6_deptlog.setIconTextGap(10);
        lb_leader_menu6_deptlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu6_deptlogMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu6_deptlog);

        lb_leader_menu7_deptatt.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu7_deptatt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu7_deptatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deptatt.png"))); // NOI18N
        lb_leader_menu7_deptatt.setBorder(emptyBorder);
        lb_leader_menu7_deptatt.setText("<html>부서 내<br>출퇴근 조회<html>");
        lb_leader_menu7_deptatt.setIconTextGap(10);
        lb_leader_menu7_deptatt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu7_deptattMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu7_deptatt);

        lb_leader_menu8_deptvacation.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu8_deptvacation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu8_deptvacation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deptvacation.png"))); // NOI18N
        lb_leader_menu8_deptvacation.setBorder(emptyBorder);
        lb_leader_menu8_deptvacation.setText("<html>부서 내<br>휴가 결재<html>");
        lb_leader_menu8_deptvacation.setIconTextGap(10);
        lb_leader_menu8_deptvacation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu8_deptvacationMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu8_deptvacation);

        lb_leader_menu9_deptemp.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu9_deptemp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_leader_menu9_deptemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deptemp.png"))); // NOI18N
        lb_leader_menu9_deptemp.setBorder(emptyBorder);
        lb_leader_menu9_deptemp.setText("<html>부서 내<br>구성원 조회<html>");
        lb_leader_menu9_deptemp.setIconTextGap(10);
        lb_leader_menu9_deptemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu9_deptempMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu9_deptemp);

        lb_leader_menu10_logout.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_leader_menu10_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_leader_menu10_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        lb_leader_menu10_logout.setBorder(emptyBorder);
        lb_leader_menu10_logout.setText("로그아웃");
        lb_leader_menu10_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_leader_menu10_logoutMouseClicked(evt);
            }
        });
        menu_leader.add(lb_leader_menu10_logout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menu_leader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menu_leader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb_leader_menu1_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu1_mainMouseClicked
        A_card1 card1 = new A_card1();
        Background.content_card.add(card1, "A_card1");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "A_card1");
    }//GEN-LAST:event_lb_leader_menu1_mainMouseClicked

    private void lb_leader_menu2_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu2_logMouseClicked
        A_card2 card2 = new A_card2();
        Background.content_card.add(card2, "A_card2");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "A_card2");
    	
    }//GEN-LAST:event_lb_leader_menu2_logMouseClicked

    private void lb_leader_menu3_attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu3_attendanceMouseClicked
        A_card3 card3 = new A_card3();
        Background.content_card.add(card3, "A_card3");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "A_card3");
    }//GEN-LAST:event_lb_leader_menu3_attendanceMouseClicked

    private void lb_leader_menu4_fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu4_fileMouseClicked
        A_card4 card4 = new A_card4();
        Background.content_card.add(card4, "A_card4");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "A_card4");
    }//GEN-LAST:event_lb_leader_menu4_fileMouseClicked

    private void lb_leader_menu5_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu5_viewMouseClicked
        A_card5 card5 = new A_card5();
        Background.content_card.add(card5, "A_card5");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "A_card5");
    }//GEN-LAST:event_lb_leader_menu5_viewMouseClicked

    private void lb_leader_menu6_deptlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu6_deptlogMouseClicked
        B_card1 card1 = new B_card1();
        Background.content_card.add(card1, "B_card1");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "B_card1");
    }//GEN-LAST:event_lb_leader_menu6_deptlogMouseClicked

    private void lb_leader_menu7_deptattMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu7_deptattMouseClicked
        B_card2 card2 = new B_card2();
        Background.content_card.add(card2, "B_card2");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "B_card2");
    }//GEN-LAST:event_lb_leader_menu7_deptattMouseClicked

    private void lb_leader_menu8_deptvacationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu8_deptvacationMouseClicked
        B_card3 card3 = new B_card3();
        Background.content_card.add(card3, "B_card3");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "B_card3");
    }//GEN-LAST:event_lb_leader_menu8_deptvacationMouseClicked

    private void lb_leader_menu9_deptempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu9_deptempMouseClicked
        B_card4 card4 = new B_card4();
        Background.content_card.add(card4, "B_card4");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "B_card4");
    }//GEN-LAST:event_lb_leader_menu9_deptempMouseClicked

    private void lb_leader_menu10_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_leader_menu10_logoutMouseClicked
        CardLayout card = (CardLayout) Login.login_card.getLayout();
        card.show(Login.login_card, "login");
    }//GEN-LAST:event_lb_leader_menu10_logoutMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_leader_menu10_logout;
    private javax.swing.JLabel lb_leader_menu1_main;
    private javax.swing.JLabel lb_leader_menu2_log;
    private javax.swing.JLabel lb_leader_menu3_attendance;
    private javax.swing.JLabel lb_leader_menu4_file;
    private javax.swing.JLabel lb_leader_menu5_view;
    private javax.swing.JLabel lb_leader_menu6_deptlog;
    private javax.swing.JLabel lb_leader_menu7_deptatt;
    private javax.swing.JLabel lb_leader_menu8_deptvacation;
    private javax.swing.JLabel lb_leader_menu9_deptemp;
    private javax.swing.JLabel lb_leader_menu_title;
    private javax.swing.JPanel menu_leader;
    // End of variables declaration//GEN-END:variables
}
