/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import javax.swing.border.EmptyBorder;
import java.awt.CardLayout;

/**
 *
 * @author 20191
 */
public class Menu_manager extends javax.swing.JPanel {

    public Menu_manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_manager = new javax.swing.JPanel();
        lb_manager_menu_title = new javax.swing.JLabel();
        lb_manager_menu1_emp = new javax.swing.JLabel();
        lb_manager_menu2_deptatt = new javax.swing.JLabel();
        empty5 = new javax.swing.JLabel();
        empty6 = new javax.swing.JLabel();
        empty7 = new javax.swing.JLabel();
        empty8 = new javax.swing.JLabel();
        empty9 = new javax.swing.JLabel();
        empty10 = new javax.swing.JLabel();
        empty11 = new javax.swing.JLabel();
        lb_manager_menu3_logout = new javax.swing.JLabel();
        EmptyBorder emptyBorder = new EmptyBorder(200, 10, 200, 10);

        setMaximumSize(new java.awt.Dimension(200, 700));
        setMinimumSize(new java.awt.Dimension(200, 700));
        setPreferredSize(new java.awt.Dimension(200, 700));

        menu_manager.setBackground(new java.awt.Color(102, 102, 102));
        menu_manager.setMaximumSize(new java.awt.Dimension(200, 700));
        menu_manager.setMinimumSize(new java.awt.Dimension(200, 700));
        menu_manager.setPreferredSize(new java.awt.Dimension(200, 700));
        menu_manager.setLayout(new java.awt.GridLayout(11, 1));

        lb_manager_menu_title.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lb_manager_menu_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_manager_menu_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/title.png"))); // NOI18N
        lb_manager_menu_title.setText(" 메뉴");
        menu_manager.add(lb_manager_menu_title);

        lb_manager_menu1_emp.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_manager_menu1_emp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_manager_menu1_emp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emp.png"))); // NOI18N
        lb_manager_menu1_emp.setBorder(emptyBorder);
        lb_manager_menu1_emp.setText("구성원 관리");
        lb_manager_menu1_emp.setToolTipText("");
        lb_manager_menu1_emp.setIconTextGap(10);
        lb_manager_menu1_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_manager_menu1_empMouseClicked(evt);
            }
        });
        menu_manager.add(lb_manager_menu1_emp);

        lb_manager_menu2_deptatt.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_manager_menu2_deptatt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_manager_menu2_deptatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deptatt.png"))); // NOI18N
        lb_manager_menu2_deptatt.setBorder(emptyBorder);
        lb_manager_menu2_deptatt.setText("<html>부서별<br>근태 기록</html>");
        lb_manager_menu2_deptatt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_manager_menu2_deptatt.setIconTextGap(10);
        lb_manager_menu2_deptatt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_manager_menu2_deptattMouseClicked(evt);
            }
        });
        menu_manager.add(lb_manager_menu2_deptatt);

        empty5.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        empty5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_manager.add(empty5);

        empty6.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        empty6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_manager.add(empty6);

        empty7.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        empty7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_manager.add(empty7);

        empty8.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        empty8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_manager.add(empty8);

        empty9.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        empty9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_manager.add(empty9);

        empty10.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        empty10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_manager.add(empty10);

        empty11.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        empty11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_manager.add(empty11);

        lb_manager_menu3_logout.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lb_manager_menu3_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_manager_menu3_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        lb_manager_menu3_logout.setText("로그아웃");
        lb_manager_menu3_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_manager_menu3_logoutMouseClicked(evt);
            }
        });
        menu_manager.add(lb_manager_menu3_logout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menu_manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menu_manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb_manager_menu1_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_manager_menu1_empMouseClicked
        C_card1 card1 = new C_card1();
        Background.content_card.add(card1, "C_card1");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "C_card1");
    }//GEN-LAST:event_lb_manager_menu1_empMouseClicked

    private void lb_manager_menu2_deptattMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_manager_menu2_deptattMouseClicked
        C_card2 card2 = new C_card2();
        Background.content_card.add(card2, "C_card2");
    	CardLayout card = (CardLayout)Background.content_card.getLayout();
    	card.show(Background.content_card, "C_card2");
    }//GEN-LAST:event_lb_manager_menu2_deptattMouseClicked

    private void lb_manager_menu3_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_manager_menu3_logoutMouseClicked
        CardLayout card = (CardLayout) Login.login_card.getLayout();
        card.show(Login.login_card, "login");
    }//GEN-LAST:event_lb_manager_menu3_logoutMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel empty5;
    private javax.swing.JLabel empty6;
    private javax.swing.JLabel empty7;
    private javax.swing.JLabel empty8;
    private javax.swing.JLabel empty9;
    private javax.swing.JLabel empty10;
    private javax.swing.JLabel empty11;
    private javax.swing.JLabel lb_manager_menu1_emp;
    private javax.swing.JLabel lb_manager_menu2_deptatt;
    private javax.swing.JLabel lb_manager_menu3_logout;
    private javax.swing.JLabel lb_manager_menu_title;
    private javax.swing.JPanel menu_manager;
    // End of variables declaration//GEN-END:variables
}
